import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs.recommended,
  prettier,
  ...svelte.configs.prettier,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        // `google` is the ambient Google Maps namespace from @types/google.maps. It
        // is used in type positions only, but ESLint cannot tell those apart.
        // `__GIT_SHA__` is substituted by Vite's `define` at build time, so it is a
        // real global at runtime but exists in no file for ESLint to find.
        google: 'readonly',
        __GIT_SHA__: 'readonly',
        __APP_VERSION__: 'readonly'
      }
    }
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.svelte'],
        parser: ts.parser
      }
    }
  },
  {
    // coverage/ is generated by `npm run coverage`; it is gitignored, but flat
    // config does not read .gitignore, so it has to be listed here too.
    ignores: ['build/', '.svelte-kit/', 'node_modules/', 'ios/', 'android/', 'dist/', 'coverage/']
  }
);
