import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

export default ts.config(
  js.configs.recommended,
  ...ts.configs.recommended,
  ...svelte.configs.recommended,
  prettier,
  ...svelte.configs.prettier,
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        // The Maps SDK namespace, from @types/google.maps. Declared here because
        // `no-undef` cannot see a TypeScript type annotation as anything other
        // than an undefined identifier, and it is a genuine runtime global once
        // the SDK has loaded.
        google: 'readonly'
      }
    }
  },
  {
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.svelte'],
        parser: ts.parser
      }
    }
  },
  {
    // `coverage/` is generated by `npm run coverage`; it is gitignored, but flat
    // config does not read .gitignore, so it has to be listed here too.
    ignores: ['build/', '.svelte-kit/', 'node_modules/', 'ios/', 'android/', 'dist/', 'coverage/']
  }
);
